export const GLOSSARY = [
  { term: 'Brainwave (onda cerebral)', body: 'Frecuencia eléctrica del cerebro que querés inducir. No se escucha directamente porque está por debajo de 20 Hz; se "monta" sobre el carrier.' },
  { term: 'Carrier (portadora)', body: 'El tono audible que sí escuchás. Es el vehículo que transporta la frecuencia cerebral. Elegí una que te resulte agradable.' },
  { term: 'a-mod (amplitud)', body: 'Modula el volumen del carrier a la frecuencia cerebral. Crea tonos isocrónicos. Funciona con un solo parlante. En el radar se ve como un anillo que late.' },
  { term: 'binaural', body: 'Divide el carrier en dos tonos: uno para cada oído, con una diferencia igual a la frecuencia cerebral. El beat lo crea tu cerebro. Necesitás auriculares. En el radar se ve como dos lóbulos sobre los oídos.' },
  { term: 'stereo (bilateral)', body: 'Mueve el sonido de izquierda a derecha a la frecuencia cerebral. Crea beats bilaterales. En el radar se ve como una banda horizontal con el punto barriendo L↔R.' },
  { term: 'f-mod (frecuencia)', body: 'Mueve el pitch del carrier alrededor de su frecuencia central. El más audible de los cuatro, pero también el más fatigante. En el radar se muestra como desplazamiento frente↔atrás.' },
  { term: 'Noise (portadora de ruido)', body: 'Ruido filtrado alrededor de la frecuencia carrier. Se mezcla con la senoide: a 0% predomina el tono y a 100% predomina la textura filtrada. f-mod también mueve el centro del filtro. En el radar se ve como una nube difusa alrededor de la cabeza.' },
  { term: 'Mix', body: 'Nivel general de salida. Controla el volumen final de todo lo que suena.' },
  { term: 'Detener suave', body: 'Al detener la escucha individual o el timeline, la app puede caer primero a una banda elegida (Delta/Theta/Alpha/Beta/Gamma) y hacer un fade del mix antes de cortar el audio. El objetivo es evitar un corte brusco; no representa un protocolo clínico ni una promesa terapéutica.' },
  { term: 'Transición suave', body: 'En la línea de tiempo, mueve gradualmente los ocho parámetros de audio del paso saliente al entrante durante los segundos que elijas (0 a 60), en lugar de cortar en seco. Mientras dura, el estado lo indica con "· transición". Es comodidad de escucha: no representa un protocolo clínico ni un efecto médico.' },
  { term: 'Reloj de la línea de tiempo', body: 'La secuencia avanza con el reloj del contexto de audio, no con temporizadores de la página. Por eso los pasos cambian igual con la ventana minimizada o la pestaña en segundo plano, aunque la interfaz se repinte al volver. El retraso de una transición está acotado por el intervalo de actualización (unos 60 ms) y no se acumula de un paso al siguiente. Al volver de segundo plano solo se aplica el paso que corresponde al momento actual, no los que quedaron atrás.' },
  { term: 'Dock del timeline', body: 'La línea de tiempo vive en un panel fijo abajo de la app, siempre visible, en lugar de una ventana emergente. Se pliega y despliega con el botón ⌁ Timeline y la app recuerda tu preferencia. Plegado ocupa una franja fina con el transporte y una barra de progreso; desplegado muestra la regla de tiempos, los clips y la tira para agregar pasos. Nada de lo demás queda tapado.' },
  { term: 'Playhead', body: 'La línea ámbar que recorre los clips mientras suena la secuencia. Su posición sale del reloj de audio de la línea de tiempo, así que avanza igual con la pestaña en segundo plano y, al volver, muestra la posición real. En loop vuelve a arrancar desde el primer clip.' },
  { term: 'Gestos del dock', body: 'Arrastrás un clip horizontalmente para reordenar la secuencia y su borde derecho para cambiar la duración, con ajuste a valores redondos (1 s, o 30 s si estás en minutos). Si preferís teclado: seleccioná el clip con click y usá los botones de mover y el editor de duración del inspector; producen el mismo resultado.' },
  { term: 'Bandas cerebrales', body: 'Delta (sueño profundo), Theta (duermevela), Alpha (relajación despierta), Beta (foco), Gamma (procesamiento rápido).' },
  { term: 'Reentrenamiento auditivo', body: 'Técnica que usa un carrier ultrasónico (~14 kHz) con f-mod alto, barriendo frecuencias. Se usa para tinnitus. No está implementado en esta versión.' }
];
